filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: minio
repositories:
- name: minio
  url: https://operator.min.io/
releases:
- chart: minio/minio-operator
  name: minio-operator
  values:
  - jx-values.yaml
- chart: ../../charts/minio-tenant
  name: minio-tenant
  values:
  - jx-values.yaml
templates: {}
renderedvalues: {}
